#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Menu/Index.cshtml")]
    public partial class _Views_Menu_Index_cshtml : System.Web.Mvc.WebViewPage<Senparc.Weixin.MP.Entities.GetMenuResult>
    {
        public _Views_Menu_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Menu\Index.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>微信菜单</title>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 232), Tuple.Create("\"", 258)
, Tuple.Create(Tuple.Create("", 239), Tuple.Create<System.Object, System.Int32>(Href("~/content/reset.css")
, 239), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 290), Tuple.Create("\"", 316)
, Tuple.Create(Tuple.Create("", 297), Tuple.Create<System.Object, System.Int32>(Href("~/content/style.css")
, 297), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 348), Tuple.Create("\"", 396)
, Tuple.Create(Tuple.Create("", 355), Tuple.Create<System.Object, System.Int32>(Href("~/Res/danktooltip/css/darktooltip.min.css")
, 355), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 430), Tuple.Create("\"", 464)
, Tuple.Create(Tuple.Create("", 436), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/modernizr-2.8.3.js")
, 436), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 488), Tuple.Create("\"", 517)
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-min.js")
, 494), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 541), Tuple.Create("\"", 593)
, Tuple.Create(Tuple.Create("", 547), Tuple.Create<System.Object, System.Int32>(Href("~/Res/danktooltip/js/jquery.darktooltip.min.js")
, 547), false)
);

WriteLiteral(@"></script>
</head>
<body>
    <style>
        .txtButton { width: 120px; }

        select.dllButtonDetails { padding: 5px; }

            select.dllButtonDetails option { padding: 5px; }

        .txtButtonDetails { width: 200px; }

        .txtToken { width: 80%; }

        .submitArea { clear: both; }

        .leftArea { width: 450px; }
    </style>
    
    <div");

WriteLiteral(" class=\"wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"menuLogin\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                <ul>\r\n                    <li>\r\n                        <div");

WriteLiteral(" class=\"control-head\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-title\"");

WriteLiteral(">获取AccessToken</label>\r\n                        </div>\r\n                    </li>" +
"\r\n                    <li>\r\n                        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">AppId:</label>\r\n                        <input");

WriteLiteral(" class=\"control-input\"");

WriteLiteral(" id=\"menuLogin_AppId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n                    </li>\r\n                    <li>\r\n                       " +
" <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">AppSecret:</label>\r\n                        <input");

WriteLiteral(" class=\"control-input\"");

WriteLiteral(" id=\"menuLogin_AppSecret\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n                    </li>\r\n                    <li>\r\n                       " +
" <button");

WriteLiteral(" class=\"control-btn\"");

WriteLiteral(" id=\"menuLogin_Submit\"");

WriteLiteral(">获取AccessToken</button>\r\n                    </li>\r\n                    <li>\r\n   " +
"                     <p");

WriteLiteral(" class=\"control-p\"");

WriteLiteral(">注：</p>\r\n                        <p");

WriteLiteral(" class=\"control-p\"");

WriteLiteral(">1.使用菜单需要成为“服务号”，或通过认证的“订阅号”。到微信后台【高级功能>开发模式】下获取信息</p>\r\n                        <" +
"p");

WriteLiteral(" class=\"control-p\"");

WriteLiteral(">2.这里的Token已经使用AccessTokenContainer管理起来，有效期内不会重复获取，过了有效期自动获取。也就是说如果已经在本网页上获取一次，接下" +
"去只需要提供AppId即可（直到服务器重启或列队过长被清理）</p>\r\n                    </li>\r\n                <" +
"/ul>\r\n                <p");

WriteLiteral(" style=\"padding: 15px 20px; font-size: 16px;\"");

WriteLiteral(">或：</p>\r\n                <ul>\r\n                    <li>\r\n                        " +
"<div");

WriteLiteral(" class=\"control-head\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-title\"");

WriteLiteral(">我有当前可用Token</label>\r\n                        </div>\r\n                    </li>\r\n" +
"                    <li>\r\n                        <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Token:</label>\r\n                        <input");

WriteLiteral(" class=\"control-input\"");

WriteLiteral(" id=\"menuLogin_OldToken\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n                    </li>\r\n                    <li>\r\n                       " +
" <button");

WriteLiteral(" class=\"control-btn\"");

WriteLiteral(" id=\"menuLogin_SubmitOldToken\"");

WriteLiteral(">直接使用</button>\r\n                    </li>\r\n                    <li>\r\n            " +
"            <p");

WriteLiteral(" class=\"control-p\"");

WriteLiteral(">注：这个Token是通过AppId和AppSecret得到的自动生成的Token。</p>\r\n                    </li>\r\n      " +
"          </ul>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"up-experience\"");

WriteLiteral(">\r\n                    <p>微微嗨已全面支持二级菜单、点击事件和访问网页</p>\r\n                    <p>让微微嗨" +
"为您的微信账号做一次全面升级，获得更多菜单功能！</p>\r\n                    <img");

WriteLiteral(" src=\"/images/v2/menu-up.png\"");

WriteLiteral(" />\r\n                    <p><a");

WriteLiteral(" href=\"http://www.weiweihi.com\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(">点击这开始体验</a></p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n   " +
"     <div");

WriteLiteral(" id=\"menuEditor\"");

WriteLiteral(@">
            <h3>使用说明及规则，请仔细阅读</h3>
            <ul>
                <li>官方要求：一级菜单按钮个数为2-3个</li>
                <li>官方要求：如果设置了二级菜单，子按钮个数为2-5个</li>
                <li>官方要求：按钮描述，既按钮名字，不超过16个字节，子菜单不超过40个字节</li>
                <li>如果name不填，此按钮将被忽略</li>
                <li>如果一级菜单为空，该列所有设置的二级菜单都会被忽略</li>
                <li>key仅在SingleButton（单击按钮，无下级菜单）的状态下设置，如果此按钮有下级菜单，key将被忽略</li>
                <li>所有二级菜单都为SingleButton</li>
                <li>如果要快速看到微信上的菜单最新状态，需要重新关注，否则需要静静等待N小时</li>
            </ul>
            <p></p>
            <h3>编辑工具</h3>
");

            
            #line 103 "..\..\Views\Menu\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Menu\Index.cshtml"
             using (Html.BeginForm("CreateMenu", "Menu", FormMethod.Post, new { id = "form_Menu" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <p>\r\n                    当前Token:\r\n                    <input");

WriteLiteral(" id=\"tokenStr\"");

WriteLiteral(" name=\"token\"");

WriteLiteral(" class=\"control-input\"");

WriteLiteral(" style=\"width: 900px;\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" /><br />\r\n                </p>\r\n");

WriteLiteral("                <p>\r\n                    <input");

WriteLiteral(" id=\"btnGetMenu\"");

WriteLiteral(" class=\"control-btn\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"获取当前菜单\"");

WriteLiteral(" />\r\n                    <input");

WriteLiteral(" id=\"btnDeleteMenu\"");

WriteLiteral(" class=\"control-btn\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" value=\"删除菜单\"");

WriteLiteral(" />\r\n                </p>\r\n");

WriteLiteral("                <p");

WriteLiteral(" class=\"menu-state\"");

WriteLiteral(">\r\n                    操作状态：<strong");

WriteLiteral(" id=\"menuState\"");

WriteLiteral(">-</strong>\r\n                </p>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"float-left menu-list\"");

WriteLiteral(@">
                    <table>
                        <thead>
                            <tr>
                                <th></th>
                                <th>第一列</th>
                                <th>第二列</th>
                                <th>第三列</th>
                            </tr>
                        </thead>
                        <tbody>
");

            
            #line 127 "..\..\Views\Menu\Index.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 127 "..\..\Views\Menu\Index.cshtml"
                             for (int i = 0; i < 6; i++)
                            {
                                var isRootMenu = i == 5;

            
            #line default
            #line hidden
WriteLiteral("                                <tr");

WriteAttribute("id", Tuple.Create(" id=\"", 5445), Tuple.Create("\"", 5499)
            
            #line 130 "..\..\Views\Menu\Index.cshtml"
, Tuple.Create(Tuple.Create("", 5450), Tuple.Create<System.Object, System.Int32>(isRootMenu ? "subMenuRow_" + i : "rootMenuRow"
            
            #line default
            #line hidden
, 5450), false)
);

WriteLiteral(">\r\n                                    <td>\r\n");

WriteLiteral("                                        ");

            
            #line 132 "..\..\Views\Menu\Index.cshtml"
                                    Write(isRootMenu ? "一级菜单按钮" : ("二级菜单No." + (i + 1)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </td>\r\n");

            
            #line 134 "..\..\Views\Menu\Index.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 134 "..\..\Views\Menu\Index.cshtml"
                                     for (int j = 0; j < 3; j++)
                                    {
                                        var namePrefix = isRootMenu ? string.Format("menu.button[{0}]", j) : string.Format("menu.button[{0}].sub_button[{1}]", j, i);
                                        var idPrefix = isRootMenu ? string.Format("menu_button{0}", j) : string.Format("menu_button{0}_sub_button{1}", j, i);

            
            #line default
            #line hidden
WriteLiteral("                                        <td>\r\n                                   " +
"         <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" class=\"control-input\"");

WriteAttribute("name", Tuple.Create(" name=\"", 6241), Tuple.Create("\"", 6265)
            
            #line 139 "..\..\Views\Menu\Index.cshtml"
              , Tuple.Create(Tuple.Create("", 6248), Tuple.Create<System.Object, System.Int32>(namePrefix
            
            #line default
            #line hidden
, 6248), false)
, Tuple.Create(Tuple.Create("", 6261), Tuple.Create(".key", 6261), true)
);

WriteAttribute("id", Tuple.Create(" id=\"", 6266), Tuple.Create("\"", 6286)
            
            #line 139 "..\..\Views\Menu\Index.cshtml"
                                     , Tuple.Create(Tuple.Create("", 6271), Tuple.Create<System.Object, System.Int32>(idPrefix
            
            #line default
            #line hidden
, 6271), false)
, Tuple.Create(Tuple.Create("", 6282), Tuple.Create("_key", 6282), true)
);

WriteLiteral(" />\r\n                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" class=\"control-input\"");

WriteAttribute("name", Tuple.Create(" name=\"", 6378), Tuple.Create("\"", 6403)
            
            #line 140 "..\..\Views\Menu\Index.cshtml"
              , Tuple.Create(Tuple.Create("", 6385), Tuple.Create<System.Object, System.Int32>(namePrefix
            
            #line default
            #line hidden
, 6385), false)
, Tuple.Create(Tuple.Create("", 6398), Tuple.Create(".type", 6398), true)
);

WriteAttribute("id", Tuple.Create(" id=\"", 6404), Tuple.Create("\"", 6425)
            
            #line 140 "..\..\Views\Menu\Index.cshtml"
                                      , Tuple.Create(Tuple.Create("", 6409), Tuple.Create<System.Object, System.Int32>(idPrefix
            
            #line default
            #line hidden
, 6409), false)
, Tuple.Create(Tuple.Create("", 6420), Tuple.Create("_type", 6420), true)
);

WriteLiteral(" value=\"click\"");

WriteLiteral(" />\r\n                                            <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" class=\"control-input\"");

WriteAttribute("name", Tuple.Create(" name=\"", 6531), Tuple.Create("\"", 6555)
            
            #line 141 "..\..\Views\Menu\Index.cshtml"
              , Tuple.Create(Tuple.Create("", 6538), Tuple.Create<System.Object, System.Int32>(namePrefix
            
            #line default
            #line hidden
, 6538), false)
, Tuple.Create(Tuple.Create("", 6551), Tuple.Create(".url", 6551), true)
);

WriteAttribute("id", Tuple.Create(" id=\"", 6556), Tuple.Create("\"", 6576)
            
            #line 141 "..\..\Views\Menu\Index.cshtml"
                                     , Tuple.Create(Tuple.Create("", 6561), Tuple.Create<System.Object, System.Int32>(idPrefix
            
            #line default
            #line hidden
, 6561), false)
, Tuple.Create(Tuple.Create("", 6572), Tuple.Create("_url", 6572), true)
);

WriteLiteral(" />\r\n                                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"control-input\"");

WriteAttribute("name", Tuple.Create(" name=\"", 6666), Tuple.Create("\"", 6691)
            
            #line 142 "..\..\Views\Menu\Index.cshtml"
            , Tuple.Create(Tuple.Create("", 6673), Tuple.Create<System.Object, System.Int32>(namePrefix
            
            #line default
            #line hidden
, 6673), false)
, Tuple.Create(Tuple.Create("", 6686), Tuple.Create(".name", 6686), true)
);

WriteAttribute("id", Tuple.Create(" id=\"", 6692), Tuple.Create("\"", 6713)
            
            #line 142 "..\..\Views\Menu\Index.cshtml"
                                    , Tuple.Create(Tuple.Create("", 6697), Tuple.Create<System.Object, System.Int32>(idPrefix
            
            #line default
            #line hidden
, 6697), false)
, Tuple.Create(Tuple.Create("", 6708), Tuple.Create("_name", 6708), true)
);

WriteLiteral(" class=\"txtButton\"");

WriteLiteral(" data-i=\"");

            
            #line 142 "..\..\Views\Menu\Index.cshtml"
                                                                                                                                                          Write(i);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-j=\"");

            
            #line 142 "..\..\Views\Menu\Index.cshtml"
                                                                                                                                                                      Write(j);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 142 "..\..\Views\Menu\Index.cshtml"
                                                                                                                                                                          Write(Html.Raw(isRootMenu ? string.Format(@"data-root=""{0}""", j) : ""));

            
            #line default
            #line hidden
WriteLiteral(" />\r\n                                        </td>\r\n");

            
            #line 144 "..\..\Views\Menu\Index.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </tr>\r\n");

            
            #line 146 "..\..\Views\Menu\Index.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tbody>\r\n                    </table>\r\n                <" +
"/div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"float-left\"");

WriteLiteral(" id=\"buttonDetails\"");

WriteLiteral(">\r\n                    <h3>按钮其他参数</h3>\r\n                    <p>Name：<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"buttonDetails_name\"");

WriteLiteral(" class=\"control-input txtButton\"");

WriteLiteral(" disabled=\"disabled\"");

WriteLiteral(" /></p>\r\n                    <p>\r\n                        Type：\r\n                " +
"        <select");

WriteLiteral(" id=\"buttonDetails_type\"");

WriteLiteral(" class=\"dllButtonDetails\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"click\"");

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">点击事件（传回服务器）</option>\r\n                            <option");

WriteLiteral(" value=\"view\"");

WriteLiteral(">访问网页（直接跳转）</option>\r\n                            <option");

WriteLiteral(" value=\"location_Select\"");

WriteLiteral(">弹出地理位置选择器</option>\r\n                            <option");

WriteLiteral(" value=\"pic_photo_or_album\"");

WriteLiteral(">弹出拍照或者相册发图</option>\r\n                            <option");

WriteLiteral(" value=\"pic_sysphoto\"");

WriteLiteral(">弹出系统拍照发图</option>\r\n                            <option");

WriteLiteral(" value=\"pic_weixin\"");

WriteLiteral(">弹出微信相册发图器</option>\r\n                            <option");

WriteLiteral(" value=\"scancode_push\"");

WriteLiteral(">扫码推事件</option>\r\n                            <option");

WriteLiteral(" value=\"scancode_waitmsg\"");

WriteLiteral(">扫码推事件且弹出“消息接收中”提示框</option>\r\n                        </select>\r\n                " +
"    </p>\r\n                    <p");

WriteLiteral(" id=\"buttonDetails_key_area\"");

WriteLiteral(">\r\n                        Key：<input");

WriteLiteral(" id=\"buttonDetails_key\"");

WriteLiteral(" class=\"control-input txtButtonDetails\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n                    </p>\r\n                    <p");

WriteLiteral(" id=\"buttonDetails_url_area\"");

WriteLiteral(">\r\n                        Url：<input");

WriteLiteral(" id=\"buttonDetails_url\"");

WriteLiteral(" class=\"control-input txtButtonDetails\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" />\r\n                    </p>\r\n                    <p>\r\n                        如" +
"果还有下级菜单请忽略Type和Key、Url。<br />\r\n                    </p>\r\n                </div>\r" +
"\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" id=\"submitArea\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"control-btn\"");

WriteLiteral(" value=\"更新到服务器\"");

WriteLiteral(" id=\"submitMenu\"");

WriteLiteral(" />\r\n                </div>\r\n");

            
            #line 180 "..\..\Views\Menu\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n    </div>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8949), Tuple.Create("\"", 9003)
            
            #line 184 "..\..\Views\Menu\Index.cshtml"
, Tuple.Create(Tuple.Create("", 8955), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/Weixin/senparc.menu.js")
            
            #line default
            #line hidden
, 8955), false)
);

WriteLiteral("></script>\r\n    <script>\r\n        $(function () {\r\n            senparc.menu.init(" +
");\r\n        });\r\n    </script>\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
